<Project>
  <PropertyGroup>
    <NeonMixPackages>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..\.local\windows-driver-sdk\'))</NeonMixPackages>
  </PropertyGroup>
  <Import Project="$(NeonMixPackages)Microsoft.Windows.WDK.x64.10.0.26100.6584\build\native\Microsoft.Windows.WDK.x64.props" Condition="Exists('$(NeonMixPackages)Microsoft.Windows.WDK.x64.10.0.26100.6584\build\native\Microsoft.Windows.WDK.x64.props')" />
  <Import Project="$(NeonMixPackages)Microsoft.Windows.SDK.CPP.x64.10.0.26100.6584\build\native\Microsoft.Windows.SDK.cpp.x64.props" Condition="Exists('$(NeonMixPackages)Microsoft.Windows.SDK.CPP.x64.10.0.26100.6584\build\native\Microsoft.Windows.SDK.cpp.x64.props')" />
  <Import Project="$(NeonMixPackages)Microsoft.Windows.SDK.CPP.10.0.26100.6584\build\native\Microsoft.Windows.SDK.cpp.props" Condition="Exists('$(NeonMixPackages)Microsoft.Windows.SDK.CPP.10.0.26100.6584\build\native\Microsoft.Windows.SDK.cpp.props')" />
</Project>
