//! Parent/child media transport. Only the current user and the expected worker
//! PID may connect. Endpoints are generated by the Hub, never accepted via API.
#[cfg(unix)]
#[path = "local_unix.rs"]
mod implementation;
#[cfg(windows)]
#[path = "local_windows.rs"]
mod implementation;
pub use implementation::{Listener, Stream};

fn validate_nonce(nonce: &str) -> std::io::Result<()> {
    if nonce.len() != 16 || !nonce.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "invalid local media endpoint nonce",
        ));
    }
    Ok(())
}
