//! Closed public error data. No paths, names, credentials, or stderr are parameters.
use serde::{Deserialize, Deserializer, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FaultCode {
    GenericFailure,
    RevisionConflict,
    PermissionDenied,
    Unauthenticated,
    InvalidArgument,
    NotFound,
    QuotaExceeded,
    ReceiverBusy,
    RoomCapacityFull,
    SourceAlreadyActive,
    SourceBlocked,
    PairingRevoked,
    StaleRevision,
    SessionChanged,
    OutputUnavailable,
    OutputObjectReplaced,
    WorkerUnavailable,
    UpgradeRequired,
    HubPortInUse,
    MigrationRequired,
    CredentialMissing,
    CredentialPermissionDenied,
    CredentialStoreBusy,
    AdministratorCredentialProtected,
    CredentialIoFailed,
    ProfileDurabilityUnconfirmed,
    ConfigurationRecoveryRequired,
    CredentialCorrupt,
    CredentialVersionUnsupported,
    CredentialKindMismatch,
    CredentialReferenceInvalid,
    CredentialAlreadyExists,
    CredentialProfileMissing,
    SetupIncomplete,
    UnsupportedAudioFormat,
    CaptureUnavailable,
    ConnectionUnavailable,
    BackgroundTimeout,
    BackgroundBusy,
    RequestInterrupted,
    BackgroundShuttingDown,
    RuntimeUnavailable,
    ProcessAlreadyRunning,
    ProcessExited,
    StopFailed,
    StopIncomplete,
    RuntimeCleanupIncomplete,
    LifecycleOwnerLost,
    HubSetupExists,
    HubSettingsRequireStop,
    SenderRequiresHubStop,
    HubRequiresSenderStop,
    SelfConnectionForbidden,
    ResourceOwnedByOtherInstance,
    LocalFeedbackLoop,
    LocalFeedbackCheckUnavailable,
    OutputBindingRequired,
    InvalidOutputBinding,
    DiscoveryIncomplete,
    InvalidBackendResponse,
    IpcInvalidRequest,
    IpcIncompatibleVersion,
    IpcMessageTooLarge,
    InvalidPath,
    DiagnosticsSaveFailed,
    NetworkApiFailed,
    NetworkIdentityUnavailable,
    NetworkIdentityInvalid,
    NetworkTokenUnavailable,
    NetworkModuleUnavailable,
    NetworkPackagePathInvalid,
    NetworkHashUnavailable,
    NetworkPackageReadFailed,
    NetworkRecordInvalid,
    NetworkRecordWriteFailed,
    NetworkInstanceInvalid,
    NetworkInstallationInvalid,
    NetworkPackageHashMismatch,
    NetworkRequesterUnavailable,
    NetworkRequesterInvalid,
    NetworkRecordMissing,
    NetworkRuleOwnerMismatch,
    NetworkRuleReadbackFailed,
    NetworkRuleRemoveFailed,
    NetworkOperationRequired,
    NetworkOperationInvalid,
    NetworkArgumentInvalid,
    NetworkUacCancelled,
    IncompatibleVersion,
    PlaybackBlocked,
    AlreadyActive,
    IdempotencyConflict,
    SnapshotRequired,
    Busy,
    CommandIdReused,
    InvalidCommand,
    InvalidCommandId,
    InvalidGain,
    InvalidReceiverCount,
    InvalidReceiverName,
    InvalidSourceAlias,
    ProfileUnavailable,
    ProfileWriteFailed,
    ReceiverDisabled,
    ReceiverUnknown,
    SourceUnknown,
}
impl FaultCode {
    pub const ALL: &'static [Self] = &[
        Self::GenericFailure,
        Self::RevisionConflict,
        Self::PermissionDenied,
        Self::Unauthenticated,
        Self::InvalidArgument,
        Self::NotFound,
        Self::QuotaExceeded,
        Self::ReceiverBusy,
        Self::RoomCapacityFull,
        Self::SourceAlreadyActive,
        Self::SourceBlocked,
        Self::PairingRevoked,
        Self::StaleRevision,
        Self::SessionChanged,
        Self::OutputUnavailable,
        Self::OutputObjectReplaced,
        Self::WorkerUnavailable,
        Self::UpgradeRequired,
        Self::HubPortInUse,
        Self::MigrationRequired,
        Self::CredentialMissing,
        Self::CredentialPermissionDenied,
        Self::CredentialStoreBusy,
        Self::AdministratorCredentialProtected,
        Self::CredentialIoFailed,
        Self::ProfileDurabilityUnconfirmed,
        Self::ConfigurationRecoveryRequired,
        Self::CredentialCorrupt,
        Self::CredentialVersionUnsupported,
        Self::CredentialKindMismatch,
        Self::CredentialReferenceInvalid,
        Self::CredentialAlreadyExists,
        Self::CredentialProfileMissing,
        Self::SetupIncomplete,
        Self::UnsupportedAudioFormat,
        Self::CaptureUnavailable,
        Self::ConnectionUnavailable,
        Self::BackgroundTimeout,
        Self::BackgroundBusy,
        Self::RequestInterrupted,
        Self::BackgroundShuttingDown,
        Self::RuntimeUnavailable,
        Self::ProcessAlreadyRunning,
        Self::ProcessExited,
        Self::StopFailed,
        Self::StopIncomplete,
        Self::RuntimeCleanupIncomplete,
        Self::LifecycleOwnerLost,
        Self::HubSetupExists,
        Self::HubSettingsRequireStop,
        Self::SenderRequiresHubStop,
        Self::HubRequiresSenderStop,
        Self::SelfConnectionForbidden,
        Self::ResourceOwnedByOtherInstance,
        Self::LocalFeedbackLoop,
        Self::LocalFeedbackCheckUnavailable,
        Self::OutputBindingRequired,
        Self::InvalidOutputBinding,
        Self::DiscoveryIncomplete,
        Self::InvalidBackendResponse,
        Self::IpcInvalidRequest,
        Self::IpcIncompatibleVersion,
        Self::IpcMessageTooLarge,
        Self::InvalidPath,
        Self::DiagnosticsSaveFailed,
        Self::NetworkApiFailed,
        Self::NetworkIdentityUnavailable,
        Self::NetworkIdentityInvalid,
        Self::NetworkTokenUnavailable,
        Self::NetworkModuleUnavailable,
        Self::NetworkPackagePathInvalid,
        Self::NetworkHashUnavailable,
        Self::NetworkPackageReadFailed,
        Self::NetworkRecordInvalid,
        Self::NetworkRecordWriteFailed,
        Self::NetworkInstanceInvalid,
        Self::NetworkInstallationInvalid,
        Self::NetworkPackageHashMismatch,
        Self::NetworkRequesterUnavailable,
        Self::NetworkRequesterInvalid,
        Self::NetworkRecordMissing,
        Self::NetworkRuleOwnerMismatch,
        Self::NetworkRuleReadbackFailed,
        Self::NetworkRuleRemoveFailed,
        Self::NetworkOperationRequired,
        Self::NetworkOperationInvalid,
        Self::NetworkArgumentInvalid,
        Self::NetworkUacCancelled,
        Self::IncompatibleVersion,
        Self::PlaybackBlocked,
        Self::AlreadyActive,
        Self::IdempotencyConflict,
        Self::SnapshotRequired,
        Self::Busy,
        Self::CommandIdReused,
        Self::InvalidCommand,
        Self::InvalidCommandId,
        Self::InvalidGain,
        Self::InvalidReceiverCount,
        Self::InvalidReceiverName,
        Self::InvalidSourceAlias,
        Self::ProfileUnavailable,
        Self::ProfileWriteFailed,
        Self::ReceiverDisabled,
        Self::ReceiverUnknown,
        Self::SourceUnknown,
    ];
    pub fn as_str(self) -> &'static str {
        match self {
            Self::GenericFailure => "generic_failure",
            Self::RevisionConflict => "revision_conflict",
            Self::PermissionDenied => "permission_denied",
            Self::Unauthenticated => "unauthenticated",
            Self::InvalidArgument => "invalid_argument",
            Self::NotFound => "not_found",
            Self::QuotaExceeded => "quota_exceeded",
            Self::ReceiverBusy => "receiver_busy",
            Self::RoomCapacityFull => "room_capacity_full",
            Self::SourceAlreadyActive => "source_already_active",
            Self::SourceBlocked => "source_blocked",
            Self::PairingRevoked => "pairing_revoked",
            Self::StaleRevision => "stale_revision",
            Self::SessionChanged => "session_changed",
            Self::OutputUnavailable => "output_unavailable",
            Self::OutputObjectReplaced => "output_object_replaced",
            Self::WorkerUnavailable => "worker_unavailable",
            Self::UpgradeRequired => "upgrade_required",
            Self::HubPortInUse => "hub_port_in_use",
            Self::MigrationRequired => "migration_required",
            Self::CredentialMissing => "credential_missing",
            Self::CredentialPermissionDenied => "credential_permission_denied",
            Self::CredentialStoreBusy => "credential_store_busy",
            Self::AdministratorCredentialProtected => "administrator_credential_protected",
            Self::CredentialIoFailed => "credential_io_failed",
            Self::ProfileDurabilityUnconfirmed => "profile_durability_unconfirmed",
            Self::ConfigurationRecoveryRequired => "configuration_recovery_required",
            Self::CredentialCorrupt => "credential_corrupt",
            Self::CredentialVersionUnsupported => "credential_version_unsupported",
            Self::CredentialKindMismatch => "credential_kind_mismatch",
            Self::CredentialReferenceInvalid => "credential_reference_invalid",
            Self::CredentialAlreadyExists => "credential_already_exists",
            Self::CredentialProfileMissing => "credential_profile_missing",
            Self::SetupIncomplete => "setup_incomplete",
            Self::UnsupportedAudioFormat => "unsupported_audio_format",
            Self::CaptureUnavailable => "capture_unavailable",
            Self::ConnectionUnavailable => "connection_unavailable",
            Self::BackgroundTimeout => "background_timeout",
            Self::BackgroundBusy => "background_busy",
            Self::RequestInterrupted => "request_interrupted",
            Self::BackgroundShuttingDown => "background_shutting_down",
            Self::RuntimeUnavailable => "runtime_unavailable",
            Self::ProcessAlreadyRunning => "process_already_running",
            Self::ProcessExited => "process_exited",
            Self::StopFailed => "stop_failed",
            Self::StopIncomplete => "stop_incomplete",
            Self::RuntimeCleanupIncomplete => "runtime_cleanup_incomplete",
            Self::LifecycleOwnerLost => "lifecycle_owner_lost",
            Self::HubSetupExists => "hub_setup_exists",
            Self::HubSettingsRequireStop => "hub_settings_require_stop",
            Self::SenderRequiresHubStop => "sender_requires_hub_stop",
            Self::HubRequiresSenderStop => "hub_requires_sender_stop",
            Self::SelfConnectionForbidden => "self_connection_forbidden",
            Self::ResourceOwnedByOtherInstance => "resource_owned_by_other_instance",
            Self::LocalFeedbackLoop => "local_feedback_loop",
            Self::LocalFeedbackCheckUnavailable => "local_feedback_check_unavailable",
            Self::OutputBindingRequired => "output_binding_required",
            Self::InvalidOutputBinding => "invalid_output_binding",
            Self::DiscoveryIncomplete => "discovery_incomplete",
            Self::InvalidBackendResponse => "invalid_backend_response",
            Self::IpcInvalidRequest => "ipc_invalid_request",
            Self::IpcIncompatibleVersion => "ipc_incompatible_version",
            Self::IpcMessageTooLarge => "ipc_message_too_large",
            Self::InvalidPath => "invalid_path",
            Self::DiagnosticsSaveFailed => "diagnostics_save_failed",
            Self::NetworkApiFailed => "network_api_failed",
            Self::NetworkIdentityUnavailable => "network_identity_unavailable",
            Self::NetworkIdentityInvalid => "network_identity_invalid",
            Self::NetworkTokenUnavailable => "network_token_unavailable",
            Self::NetworkModuleUnavailable => "network_module_unavailable",
            Self::NetworkPackagePathInvalid => "network_package_path_invalid",
            Self::NetworkHashUnavailable => "network_hash_unavailable",
            Self::NetworkPackageReadFailed => "network_package_read_failed",
            Self::NetworkRecordInvalid => "network_record_invalid",
            Self::NetworkRecordWriteFailed => "network_record_write_failed",
            Self::NetworkInstanceInvalid => "network_instance_invalid",
            Self::NetworkInstallationInvalid => "network_installation_invalid",
            Self::NetworkPackageHashMismatch => "network_package_hash_mismatch",
            Self::NetworkRequesterUnavailable => "network_requester_unavailable",
            Self::NetworkRequesterInvalid => "network_requester_invalid",
            Self::NetworkRecordMissing => "network_record_missing",
            Self::NetworkRuleOwnerMismatch => "network_rule_owner_mismatch",
            Self::NetworkRuleReadbackFailed => "network_rule_readback_failed",
            Self::NetworkRuleRemoveFailed => "network_rule_remove_failed",
            Self::NetworkOperationRequired => "network_operation_required",
            Self::NetworkOperationInvalid => "network_operation_invalid",
            Self::NetworkArgumentInvalid => "network_argument_invalid",
            Self::NetworkUacCancelled => "network_uac_cancelled",
            Self::IncompatibleVersion => "incompatible_version",
            Self::PlaybackBlocked => "playback_blocked",
            Self::AlreadyActive => "already_active",
            Self::IdempotencyConflict => "idempotency_conflict",
            Self::SnapshotRequired => "snapshot_required",
            Self::Busy => "busy",
            Self::CommandIdReused => "command_id_reused",
            Self::InvalidCommand => "invalid_command",
            Self::InvalidCommandId => "invalid_command_id",
            Self::InvalidGain => "invalid_gain",
            Self::InvalidReceiverCount => "invalid_receiver_count",
            Self::InvalidReceiverName => "invalid_receiver_name",
            Self::InvalidSourceAlias => "invalid_source_alias",
            Self::ProfileUnavailable => "profile_unavailable",
            Self::ProfileWriteFailed => "profile_write_failed",
            Self::ReceiverDisabled => "receiver_disabled",
            Self::ReceiverUnknown => "receiver_unknown",
            Self::SourceUnknown => "source_unknown",
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FaultParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Fault {
    pub code: FaultCode,
    pub params: FaultParams,
}
impl<'de> Deserialize<'de> for Fault {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Wire {
            code: FaultCode,
            params: FaultParams,
        }
        let wire = Wire::deserialize(deserializer)?;
        let valid = match wire.code {
            FaultCode::HubPortInUse => wire.params.port.is_some_and(|port| port > 0),
            _ => wire.params.port.is_none(),
        };
        if !valid {
            return Err(serde::de::Error::custom("invalid public fault parameters"));
        }
        Ok(Self {
            code: wire.code,
            params: wire.params,
        })
    }
}
impl Fault {
    pub fn new(code: FaultCode) -> Self {
        Self {
            code,
            params: FaultParams {
                port: (code == FaultCode::HubPortInUse).then_some(7443),
            },
        }
    }
    /// Legacy compatibility accepts exact machine codes or a code followed by
    /// a colon (the credential CLI's documented detail separator). Never match
    /// translated sentences, arbitrary substrings, or return the trailing data.
    pub(crate) fn from_error(error: &str) -> Option<Self> {
        serde_json::from_str::<Self>(error)
            .ok()
            .or_else(|| Self::from_machine_code(error))
    }
    pub fn from_machine_code(error: &str) -> Option<Self> {
        let code = error.split_once(':').map_or(error, |(code, _)| code).trim();
        let code: FaultCode = serde_json::from_value(Value::String(code.into())).ok()?;
        Some(Self::new(code))
    }
}
/// Fault is an additive optional field. A future backend or malformed fault must
/// not prevent the client reading otherwise valid legacy status/error data.
/// Present invalid faults become GenericFailure so unsafe parameter errors
/// cannot be accidentally remapped through legacy error text.
pub(crate) fn optional_fault<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<Fault>, D::Error> {
    let value = Option::<Value>::deserialize(deserializer)?;
    Ok(value.map(|value| {
        serde_json::from_value(value).unwrap_or_else(|_| Fault::new(FaultCode::GenericFailure))
    }))
}
