[package]
name = "neonmix-airplay-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
neonmix-core.workspace = true
neonmix-airplay-ipc = { path = "../airplay-ipc" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
